
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345678', 'Kevin Yzacupe', 'mail1@unmsm.com', 'Software'  );
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345601', 'Dollie R. Schnidt' , 'mail12@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345602', 'Cornelia J. LeClerc', 'mail13@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345603', 'Cynthia Rau', 'mail4@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345604', 'Douglas R. Cobbs', 'mail15@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345605', 'Michael Patel', 'mail16@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345606', 'Suzanne Wong' , 'mail17@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345607', 'Ivan C. Jaya' , 'mail18@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345608', 'Ida Ketterer', 'mail19@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345609', 'Laina Ochoa Lucero' , 'mail10@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345610', 'Wesley M. Montana' , 'mail11@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345611', 'Leslie F. McCleary' , 'mail12@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345612', 'Sayeed D. Mudra' , 'mail13@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345613', 'Pietronella J. Domingo' , 'mail14@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345614', 'John S. O''Leary' , 'mail15@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345615', 'Gladys D. Smith' , 'mail16@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345616', 'Sally O. Thygesen' , 'mail17@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345617', 'Rachel Vogt' , 'mail18@unmsm.com', 'Software');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345618', 'Julia DeLong' , 'mail19@unmsm.com', 'Sistemas');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345619', 'Mark T. Rizzoli' , 'mail20@unmsm.com', 'Sistemas');
insert into USUARIO (CODE, NAME, EMAIL, EAP) values ('12345620', 'Maria J. Angelo' , 'mail21@unmsm.com', 'Sistemas');
